name: .NET Core Docker (CD)

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: ubuntu-latest
    env:
      Solution_Name: DayPlannerAPI.sln
      Test_Project_Path: DayPlannerAPITests/DayPlannerAPITests.csproj
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Docker (Docker is typically pre-installed on GitHub-hosted runners)
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce

      # Log in to Docker Hub using GitHub Personal Access Token
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/dayplannerapi:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dayplannerapi:latest
