name: .NET Core Desktop

on:
  push:
    branches: [ "Continuos-Development" ]
  pull_request:
    branches: [ "Continuos-Development" ]

jobs:

  build-and-deploy:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      Solution_Name: DayPlannerAPI.sln
      Test_Project_Path: DayPlannerAPITests\DayPlannerAPITests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install Docker
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install docker-ce

    # Log in to Docker Hub using GitHub Personal Access Token
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.luukmsn }} -p ${{ secrets.C4rdB4ckR0gue }} 

    # Build and push Docker image
    - name: Build and push Docker image
      run: |
        docker build -t luukmsn/dayplannerapi:latest .
        docker push luukmsn/dayplannerapi:latest

    # Deploy Docker container
    - name: Deploy Docker container
      run: |
        docker pull luukmsn/dayplannerapi:latest
        docker stop dayplannerapi-container || true
        docker rm dayplannerapi-container || true
        docker run -d --name dayplannerapi-container -p 80:80 luukmsn/dayplannerapi:latest
